
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'taxi_rides_ny'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'taxi_rides_ny'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# Variables - can be used in models with {{ var('variable_name') }}
vars:
  # Minimum trip distance to include (in miles)
  min_trip_distance: 0.1
  # Minimum trip amount to include (in dollars)
  min_trip_amount: 2.5
  # Date range for analysis
  analysis_start_date: '2019-01-01'

# Model configurations
# We'll organize our models into three layers: staging, intermediate, and marts
models:
  taxi_rides_ny:
    staging:
      +materialized: table
      +tags: ["staging"]
    intermediate:
      +materialized: table
      +tags: ["intermediate"]
    marts:
      +materialized: table
      +tags: ["marts"]
